sfstoolbox/sfs-matlab

SFS_general/rounded_box.m, SFS_general/secondary_source_positions.m, SFS_general/tapering_window.m
Add integration weights for regular secondary source geometries based on the distance between adjacent sources along the continuous boundary. Furthermore, the tapering window is normalized such that each source is weighted (on average) with 1.0 . Both modifications should prevent amplitude fluctuations between the reproduced soundfield for different primary source positions/directions.
=> Integration weights

SFS_general/general_least_squares.m
If a fractional_delay of 0.0 is given to function, the former implementation leads to NaNs. Instead MATLAB's sinc function is used.
=> fix problem in implementation of least squares fractional delay filter

SFS_general/nfchoa_order.m
Before it was N/2, which is not identical to the cited literature (e.g. Ahrens 2012, p. 132). There it is N/2-1, which I changed the code accordingly.
Before applying this changes: was this just a mistake, or did we choose the wrong version on purpose?
=> Change Ambisonics order for even loudspeaker numbers

NEWS, SFS_config.m, SFS_time_domain/sound_field_imp_localwfs.m, SFS_time_domain/sound_field_imp_wfs.m, SFS_time_domain/wfs_fir_prefilter.m
fixes #52
* Prefilter FIR order ist stored in `conf.wfs.hpreFIRorder` 
* shall be an even integer M, resulting in a filter of length M+1
* default is M = 128
* for odd M, M+1 is used and `firls()` in `wfs_fir_prefilter()` issues a warning
* time alignment in `sound_field_imp_wfs()` and `sound_field_imp_localwfs()` will be correct nonetheless
* previously: fixed M=128 was used and the IR's last sample was discarded, resulting in a filter length of 2^7
* now: default setting uses the full length 2^7 + 1 
* rationale:
* I found the truncation a bit of a hack.
* I don't see any point in having a power-of-2 filter: 
`convolution()` is not partitioned and the length should be dominated by the wfs delays for reasonable M, `conf.N` and SSD setups.
* difference in magnitude is around -60db.
* …
=> Wfsfirprefilter

NEWS, SFS_general/secondary_source_selection.m, validation/test_secondary_source_selection.m
For some applications, e.g. local WFS, the secondary source selection is very slow. This is due to the recursive calls of ``secondary_source_selection`` and the usage of the - imho not necessary - function ``vector_product``. Furthermore ``xs`` does not need to be replicated to perform ``x0-xs``.
=> fix recursive call of selection function and remove time consuming vector product

SFS_time_domain/driving_function_imp_nfchoa.m, SFS_time_domain/driving_functions_imp/driving_function_imp_nfchoa_ps.m, SFS_time_domain/driving_functions_imp/driving_function_imp_nfchoa_pw.m
I changed the NFC-HOA time domain driving function, according to #55. But there are still some problems.
Try the following commands:
```Matlab
conf.nfchoa.order = 32;
sound_field_imp_nfchoa([-2 2],[-2 2],0,[1 0 0],'pw',300,conf)
sound_field_imp_nfchoa([-2 2],[-2 2],0,[2.5 0 0],'ps',300,conf)
```
Here are the results from before the change:
And here after the changes:
As you can see, the results for the point source is still correct, but in the case of the plane wave we have no a wrong direction.
=> Correct sign in NFC-HOA time domain driving function

SFS_time_domain/driving_function_imp_wfs.m, SFS_time_domain/sound_field_imp_wfs.m, SFS_time_domain/wfs_preequalization.m, validation/test_driving_functions_imp_with_delay.m
This is a follow up on #59.
The main goal was fomulated by @fietew as:
> Imho, it would be easier to return the pre-delay which has been added to the driving function by a particular processing step, e.g. fractional delay, wfs prefilter, focused source, plane wave, etc..
Furthermore, I would prefer that t=0 corresponds to the t=0 of the virtual source, i.e. where the sound "starts" to radiate from a point/focused source or when the plane wave passed its point of zero phase.
In order to achieve this I did the following things:
1. Add an additional `prefilter_delay` return parameter to `wfs_preequalization()`, which returns the delay that is added by the applied pre-filter.
2. Add an additional `delay_offset` return parameter to `driving_function_imp_wfs()`. In the case of …
=> Return wfs delay

SFS_general/tapering_window.m, SFS_time_domain/driving_function_imp_nfchoa.m
See https://github.com/sfstoolbox/sfs/commit/c8fec3ef82435a90c4d0a42cdb04e3de039d4566#diff-f9229d5f60cedf852a470bd907a2ac05R103 . 
The if clause in the current implementation incorrectly recognizes `edges=[1,2]` as `edges=[end,1]`
=> fix handling of edges for tapering window

SFS_monochromatic/driving_function_mono_localwfs.m
When comparing different scenarios it is difficult to retrieve the indexes of the selected secondary sources with the current version.
=> add idx to return of values local wfs driving function

SFS_time_domain/driving_function_imp_wfs.m, SFS_time_domain/driving_functions_imp/driving_function_imp_wfs_ls.m
This uses the correct distance from virtual line source to secondary sources.
(We fixed the mono-frequent case some weeks ago. This is just the same for the impulsive case.)
=> Fix 3D-WFS time domain driving function for virtual line source

SFS_plotting/draw_loudspeakers.m
With 7b46fff0839585b595f88a95ffc84e5fb3c2f9b8￼ we introduced a new weighting to the loudspeakers, which results in relatively low values (<<1) for standard setups. This is of course not a problem, but has a small effect on the plotting of real loudspeaker symbols as those are colored accordingly to the absolute weight of the loudspeaker.
Here is an example from the current master:
```Matlab
conf.plot.normalisation = 'center';
conf.plot.realloudspeakers = 1;
sound_field_mono_wfs([-2 2],[-2 2],0,[0 2.5 0],'ps',800,conf)
```
As you can see more or less all loudspeakers are white.
In this pull request I added an automatic scaling of the loudspeakers (that the maximum weight to 1) to the `draw_loudspeaker` function, which results in this plot by executing the same commands …
=> Add automatic scaling to loudspeaker weights for plotting

NEWS, SFS_config.m, SFS_general/modal_weighting.m, SFS_time_domain/driving_function_imp_nfchoa.m
in order to study the effect of different modal windows on the reproduced sound field
=> add modal weighting to time-domain nfchoa

SFS_config.m, SFS_general/delayline.m
- enable single channel signal in combination with multiple delay and weights. Resampling is hereby performed BEFORE the channel replication in order to save computation time
- fix bugs related to the 'pm' option for resampling
=> Fix bugs in delayline and improve it

SFS_ir/interpolate_ir.m
I made a small change so that there is no error if `conf.ir.useinterpolation = false` and the field `conf.ir.interpolationmethod` does not exist.
=> improve check for old config struct

NEWS, SFS_general/get_spherical_grid.m
This should fix the quadrature weights for Gauss-Legendre spherical sampling.
Below, you see how the old weights fail to ensure orthonormality.
```Matlab
Nmax = 5;
conf.secondary_sources.grid = 'gauss';
[grid,weights] = get_spherical_grid(2*(Nmax+1)^2,conf);
[phi,theta] = cart2sph(grid(:,1),grid(:,2),grid(:,3));
Ynm = [];
for n = 0:Nmax
for m = -n:n
Ynm  = [Ynm sphharmonics(n,m,theta,phi)];
end
end
inner_products = Ynm'*diag(weights)*Ynm;
figure
imagesc([0,(Nmax+1)^2],[0,(Nmax+1)^2],abs(inner_products));
xlabel('n^2 + n + m');
ylabel('n^2 + n + m');
```
=> Gauss quadrature

NEWS, SFS_ir/dummy_irs.m, SFS_time_domain/driving_functions_imp/driving_function_imp_wfs_ps.m, SFS_time_domain/wfs_fir_prefilter.m
I suggest the following changes to achieve a correct amplitude of a point source in WFS when in the time domain:
1. Correction of a mistake in the default 2.5D WFS driving function `driving_function_imp_wfs_ps()`.
2. Adding the missing amplitude terms to the FIR prefilter in `wfs_fir_prefilter()`, both for 2.5D and 3D.
3. Change amplitude and delay of `dummy_irs()` to 1/(4*pi) in 1 m distance.
These changes can be found in the three commits.
What do you think of this? Do these changes conflict with some things I missed?
=> Correct amplitude wfs time domain

NEWS, SFS_ssr/ssr_brs_wfs.m
Secondary source selection and tapering had been missing for WFS auralisation and are now added in `ssr_brs_wfs()`.
=> add secondary source selection and tapering for WFS auralisation

SFS_monochromatic/driving_functions_mono/driving_function_mono_wfs_ps.m
This updates the WFS 2.5D point source refewrence line implementation to be in line with the documentation by using abs() to make distances always positive.
=> Make WFS 2.5D ps reference line in line with doc

SFS_time_domain/driving_function_imp_nfchoa.m, SFS_time_domain/driving_functions_imp/driving_function_imp_nfchoa_fs.m, SFS_time_domain/driving_functions_imp/driving_function_imp_nfchoa_ls.m, SFS_time_domain/driving_functions_imp/driving_function_imp_nfchoa_ps.m, SFS_time_domain/driving_functions_imp/driving_function_imp_nfchoa_pw.m, SFS_time_domain/driving_functions_imp/driving_function_imp_wfs_fs.m, validation/test_imp_25d.m
According to the original publication ( see https://doi.org/10.1109/ASPAA.2011.6082325 ), Equation (10) and (11), some weights are missing in our NFCHOA time-domain implementation for the plane waves and point source. This pull request fixes this.
Execute ``test_imp_25d(true)`` to compare the spectra of 2.5D SFS techniques near the reference point with the ground truth (plane wave or point source).
There was also a bug in ``SFS_time_domain/driving_functions_imp/driving_function_imp_wfs_fs.m`` related to a wrong usage of the ``/``-operator.
=> fix wfs_fs bug and nfchoa gains

NEWS, SFS_config.m
This is a follow up of #113.
At the moment we have the default config setting:
```Matlab
conf.usebandpass = true;
conf.bandpassflow = 10;
conf.bandpassfhigh = 20000;
```
This setting results in an execution of the following line inside `sound_field_imp()`:
```Matlab
d = bandpass(d,bandpassflow,bandpassfhigh,conf);
```
in `bandpass()` the function `fir2()` is used to create the filter and applied by `convolution()`.
`sound_field_imp()` is the only place where the bandpass filtering is applied at the moment.
This pull request should figure out, why we have enabled the bandpass filtering as the **default setting** and if we can disable as default or even remove it.
=> Update usage of bandpass in sound_field_imp()

SFS_general/delayline.m, SFS_general/pm_filter.m
MATLAB's profiler told me, that the design of the resampling filter which is done in ``firpm`` for each ``delayline`` call takes at lot of time. This fix caches the filter coefficients in a persistent variable.
=> use persistent variables to speed up resampling filter

SFS_ir/get_ir.m, SFS_ir/interpolate_ir.m
I had to make a small change so that the interpolation routine is actually skipped when the desired point is contained in the selected points and no interpolation is necessary, that is one weight is 1 and the others are zero.
=> Enable shortcut for exact point

SFS_monochromatic/driving_functions_mono/driving_function_mono_wfs_vss.m, SFS_time_domain/driving_function_imp_localwfs.m
As ``x0s(:,7)`` also contains the integration weight of the secondary source, the influence of the tapering has to be computed by normalising the result to the original integration weight.
=> fix incorporation of tapering weights for LWFS

SFS_monochromatic/driving_functions_mono/driving_function_mono_wfs_fs.m, SFS_time_domain/driving_functions_imp/driving_function_imp_wfs_fs.m
I discovered an issue regarding the existing referencing scheme for the focused source in WFS, namely ``reference_point`` and ``reference_line``.
Reference Point:
```
%         _____________________
%        |      |xref-x0|
% g0 = _ |---------------------
%       \|||xref-x0| - |xs-x0||
```
Reference Line:
```
%        ______________________
% g0 = \| d_ref / (d_ref - d_s)
```
Both schemes have the drawback, that the denominator can become zero for non-pathological cases. Hence particular secondary sources have a unreasonably high amplitude. I added a scheme called ``reference_circle`` which ensure amplitude correct synthesis on a circle around the focused source, which does not have these issues. Please execute the following example to compare ``reference_point`` and …
=> Alternative referencing scheme for focused sources in WFS

validation/test_interpolation_methods.m
=> Remove x0 from interpolate_ir() call

SFS_ir/ir_correct_distance.m
In `ir_correct_distance()` we are checking if `conf.N` is long enough for the needed delay.
Delay is in seconds, but it is directly substracted from `conf.N` which is in samples.
This pull request should fix that.
=> Fix checking for correct sample length

SFS_monochromatic/driving_functions_mono/driving_function_mono_wfs_fs.m, SFS_time_domain/driving_functions_imp/driving_function_imp_wfs_fs.m
This is a follow up on #146 which introduced a fix for the 2.5D reference scheme in 2.5D as the current default implementation has the problem of possible division by 0. The resulting problems can be seen by running `test_localwfs_vss(1)` or by executing the example provided in #146.
As the proposed solution of a reference circle includes the point solution, which is currently implemented with `conf.xref` it should be ok to switch the default to this, even if the documentation is not up to date with it and we will have a new referencing scheme in 2.5 anyhow, see #136.
@fietew: if you agree with this, please "rebase and merge". If it would include more work, I would propose to postpone it also to the release 2.5.
=> Change default 2.5D WFS fs driving function

SFS_helper/progress_bar.m
This pull request is split into two commits. 2d79dcf simplifies the actual code of `progress_bar()` to allow an easier configuration of the actual progress bar. In addition, it adds an optional third argument `message` which is presented instead of the default `Progress` message.
The first commit changes nothing on the output of all the `progress_bar()` calls we have so far in the toolbox.
In the second commit (fe3a46f) I tried another progress bar style. Employing a wider bar and using only `#`. This is just an proposal, I'm not really decided if I would favor the new version over the old one ;)
@fietew: any opinion on this.
Here is an example of both styles:
```Matlab
>> for ii=1:30, progress_bar(ii,30); pause(0.1); end
```
=> Add optional message to progress_bar()

SFS_config.m, SFS_general/secondary_source_positions.m, validation/test_secondary_source_positions.m
Try:
```MATLAB
close all
clear variables
SFS_start;
conf.secondary_sources.geometry = 'linear';
conf.secondary_sources.grid = 'logarithmic';
conf.secondary_sources.logspread = 5;
idx = 0;
fdx = 1;
markers = {'diamond', 'square'};
for N0 = [20, 21]
conf.secondary_sources.number = N0;
y0 = zeros(N0,1); 
for spread = [0.1, 0.25, 0.5, 1.0, 1.5, 2.0, 5.0]
conf.secondary_sources.logspread = spread;
x0 = secondary_source_positions(conf);
y0(:) = idx;
figure(1);
hold on;
plot(x0(:,1),y0,markers{fdx});
hold off;
figure(2);
hold on;
plot(x0(2:end-1,1), ...
(x0(1:end-2,1)-x0(2:end-1,1))./(x0(2:end-1,1)-x0(3:end,1)),[markers{fdx} '-']);
hold off;
cdx = floor(N0/2)+1;
fprintf('spread: %2.2f\n', ...
(x0(end,1)-x0(end-1,1))./(x0(cdx,1)-x0(cdx-1,1)) );
idx = idx + 0.1;
end
fdx = fdx + …
```
=> Logarithmic spacing for linear secondary source distributions

SFS_general/signal_from_spectrum.m, SFS_general/spectrum_from_signal.m
Try:
```MATLAB
SFS_start;
conf.plot.useplot = true;
SOFAstart;
irs = get_ir(dummy_irs(1024,conf),[0,0,0],0,[1 0 0], 'cartesian',conf);
[b1,a1] = butter(5,0.1);
[b2,a2] = butter(10,0.2);
sig1 = filter(b1,a1,irs(:,1));
sig2 = filter(b2,a2,irs(:,1));
sig = [irs(:,1), sig1, sig2];
[amp, phase, f] = spectrum_from_signal(sig,1,conf);
sig_inv = signal_from_spectrum(amp, phase, f, 1,conf);
figure, 
plot(sig,'k');
hold on
plot(sig_inv, '--');
hold off;
[amp, phase, f] = spectrum_from_signal(sig,conf);
sig_inv = signal_from_spectrum(amp, phase, f, conf);
figure, 
plot(sig,'k');
hold on
plot(sig_inv, '--');
hold off;
[amp, phase, f] = spectrum_from_signal(sig.',2,conf);
sig_inv = signal_from_spectrum(amp, phase,f,2,conf);
figure, 
plot(sig,'k');
hold on
plot(sig_inv.', '--');
hold …
```
=> Extend spectrum_from_signal and signal_from_spectrum to multichannel signals

SFS_config.m, SFS_ir/interpolate_ir.m, validation/test_interpolation_methods.m
This is a proposal for an alternative HRTF interpolation method in the time domain:
The difference in TOAs is estimated by the maximum of the cross-correlation function. The HRIRs are then shifted to have the same TOA, interpolated and then the resulting HRIR is shifted to the interpolated TOA.
The method can handle an arbitrary number of HRIRs as input which is necessary depending on the used method for point selection.
I also added this additional method in `test_interpolation_methods()`. 
What do you think?
=> Proposed method for interpolation of HRTFs in the time domain
